apiVersion: v1
kind: Service
metadata:
  name: python-package-flask-test-service
  labels:
    run: python-package-flask-test-deployment
spec:
  type: NodePort
  selector:
    run: python-package-flask-test-deployment    
  ports:
  - port: 5000
    targetPort: http
    nodePort: 30163 #30000-32767
    protocol: TCP

