apiVersion: v1
kind: Service
metadata:
  name: python-package-flask-test-prod-az
spec:
  type: NodePort
  selector:
    app: python-package-flask-test-az
    env: prod
  ports:
  - nodePort: 32410
    protocol: TCP
    port: 5000
    targetPort: 5000

