apiVersion: v1	
kind: Service
metadata:
  labels:
    app: flask
  name: flaskapp
  namespace: flaskapp-dev
spec:
  selector:
    app: flask
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: http
    nodePort: 30163 #30000-32767
    protocol: TCP
    name: http