apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flaskapp
  namespace: flaskapp-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flaskapp
        image: ricardoahumada/flaskappforredis:latest
        ports:
        - name: http
          containerPort: 5000
