apiVersion: v1
kind: Service
metadata:
  labels:	
    app: redis
  name: redis	
  namespace: flaskapp-dev
  # selfLink: /api/v1/namespaces/default/services/redis-deployment	
spec:
  selector: 
    app: redis
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: redisport
    protocol: TCP
    name: redis  