apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dep
  namespace: flaskapp-dev
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-dep
        image: ricardoahumada/redis:latest
        ports:
        - containerPort: 6379
          name: redisport
      restartPolicy: Always
